###### Home routes ######
GET http://localhost:8080/
### 
GET https://csecontacts.onrender.com/

###### Contacts routes ######
GET http://localhost:8080/contacts/
### 
GET https://csecontacts.onrender.com/contacts/

###### Contact 1 Routes ######
GET http://localhost:8080/contacts/644c3c078989eabe6ac88ec3
### 
GET https://csecontacts.onrender.com/contacts/644c3c078989eabe6ac88ec3

###### Contact 2 Routes ######
GET http://localhost:8080/contacts/644c3c208989eabe6ac8b90f
###
GET https://csecontacts.onrender.com/contacts/644c3c208989eabe6ac8b90f

###### Contact 3 Routes ######
GET http://localhost:8080/contacts/644c3c3a8989eabe6ac8e34e
###
GET https://csecontacts.onrender.com/contacts/644c3c3a8989eabe6ac8e34e

###### Create New Contact ######
POST http://localhost:8080/contacts/ HTTP/1.1
content-type: application/json

{
  "firstName": "Bob", "lastName": "Ross", "email": "happytrees@gmail.com", "favoriteColor": "Happy Colors", "birthday": "October 29th"
}

###
POST https://csecontacts.onrender.com/contacts HTTP/1.1
content-type: application/json

{
  "firstName": "Rob", "lastName": "Boss", "email": "happyfeet@gmail.com", "favoriteColor": "Black", "birthday": "October 32nd"
}


###### Update Contact ######
PUT http://localhost:8080/contacts/645d48ecfbc1cbbe32b7fcbc HTTP/1.1
content-type: application/json

{
  "firstName": "Bob", "lastName": "O'Reily", "email": "happysquirrels@gmail.com", "favoriteColor": "Gray", "birthday": "September 19th"
}

###
PUT https://csecontacts.onrender.com/contacts/645d436e0dd15929e0d03c95 HTTP/1.1
content-type: application/json

{
  "firstName": "Rob", "lastName": "Boss", "email": "happyfeet@gmail.com", "favoriteColor": "Black", "birthday": "October 32nd"
}

###### Delete Contact ######

DELETE http://localhost:8080/contacts/645d48ecfbc1cbbe32b7fcbc HTTP/1.1

###
DELETE https://csecontacts.onrender.com/contacts/645d47df0dd15929e0d03c96 HTTP/1.1